version: '3.7'
services:
  ntpd:
    image: flee999/ntpd-bionic:latest
    container_name: ntpd-bionic
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_TIME
      - SYS_NICE
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 768M
        reservations:
          cpus: '0.50'
          memory: 512M
    volumes:
      - ./assets/ntp.conf:/etc/ntp.conf:ro
    ports:
      - "${EXPOSED_PORT}:123/udp"
    environment:
      - EXPOSED_PORT=${EXPOSED_PORT}
